---
title: "Energy Consumption"
output: html_document
date: "2022-12-08"
---

```{r, include = FALSE, echo = FALSE}
library(tidyverse)
library(jsonlite)
library(httr)
library(janitor)
library(downloadthis)
library(ggrepel)
library(data.table)
library(keyring)

today <- format(Sys.Date(), format = "%m-%d-%Y")

options(scipen = 999)

eia_key <- key_get("eia_api")

petro <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key, 
      "&facets[seriesId][]=PMTCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
      )
    )

imports <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key,
      "&facets[seriesId][]=ELNIB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
      )
  )

net_interstate <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key,
      "&facets[seriesId][]=ELISB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )

renewables <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key,
      "&facets[seriesId][]=RETCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
      )
  )

coal <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=",
      eia_key,
      "&facets[seriesId][]=CLTCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
      )
  )

gas <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key,
      "&facets[seriesId][]=NNTCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
      )
  )

nuclear <- 
  GET(
    paste0(
    "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
    eia_key,
    "&facets[seriesId][]=NUETB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )

total <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key, 
      "&facets[seriesId][]=TETCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
      )
  )

api_cleanup <- function(raw_data, fuel_type){
  
  x <- fromJSON(rawToChar(raw_data$content))
  
  x <- tibble(x$response$data) |>
    mutate(fuel = fuel_type, 
           period = as.numeric(period), 
           value = as.numeric(value)) |> 
    select(period, fuel, value)
  
  return(x)
  
}

petro <- api_cleanup(petro, "Petroleum")

imports <- api_cleanup(imports, "Imports")

net_interstate <- api_cleanup(net_interstate, "Imports")

renewables <- api_cleanup(renewables, "Renewables")

coal <- api_cleanup(coal, "Coal")

gas <- api_cleanup(gas, "Natural Gas")

nuclear <- api_cleanup(nuclear, "Nuclear")

total <- api_cleanup(total, "Total")

imports <- imports |> 
  bind_rows(net_interstate) |> 
  group_by(period) |> 
  summarise(value = sum(value)) |> 
  mutate(fuel = "Imports")

consumption_totals <- total |> 
  bind_rows(petro) |> 
  bind_rows(imports) |> 
  bind_rows(renewables) |> 
  bind_rows(coal) |> 
  bind_rows(gas) |> 
  bind_rows(nuclear)

consumption_percent <- total |> 
  bind_rows(petro) |> 
  bind_rows(imports) |> 
  bind_rows(renewables) |> 
  bind_rows(coal) |> 
  bind_rows(gas) |> 
  bind_rows(nuclear) |> 
  pivot_wider(names_from = fuel, values_from = value) |> 
  mutate(across(c(Petroleum, Imports, Renewables, Coal, `Natural Gas`, Nuclear), .fns = ~ . / Total)) |> 
  select(-c(Total)) |> 
  pivot_longer(!period, names_to = "Fuel", values_to = "Percent")

top_year <- max(consumption_totals$period)

bottom_year <- 2003 #top_year - 20

```

View Energy Consumption Data

```{r, echo = FALSE}

data_use <- consumption_totals |> 
  arrange(desc(period), fuel) |> 
  rename(`Billion BTU` = value)
  
DT::datatable(data_use, rownames = FALSE)


suppressMessages(
 data_use |> 
  download_this(
    output_name = "Minnesota Energy Consumption", 
    output_extension = ".xlsx", 
    button_label = "Download Data",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)
```

   

Energy Consumption Trend

```{r, echo = FALSE}

fuel_colors <- c("Renewables" = "#78BE21", "Nuclear" = "#008EAA", "Coal" = "#000000", "Natural Gas" = "#8D3F2B", 
                 "Imports" = "#F5E1A4", "Petroleum" = "#97999B")


p <- consumption_totals |> 
  filter(fuel != "Total", 
         period >= bottom_year) |>
  mutate(value = value / 1000) |> 
  ggplot() + aes(x = period, y = value) + geom_line(aes(colour = factor(fuel)), size = 1) + 
  scale_color_manual(values = fuel_colors, name = "") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) + xlab("Year") + ylab("Trillion BTU") + ggtitle("Minnesota Energy Consumption") +  
  scale_y_continuous() + scale_x_continuous(breaks = seq(bottom_year, top_year, by = 5), limits = c(bottom_year, top_year)) + 
  labs(caption = paste0("Source: Energy Information Administration\nAccessed ", today))

p

suppressMessages(
 p |> 
  download_this(
    output_name = "Minnesota Energy Consumption", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)

ggsave("C:/Users/dduffy/OneDrive - State of Minnesota - MN365/Frequently Used Graphs/Energy Consumption/Minnesota Energy Consumption.png", p)

```

   

Transition of Energy Consumption

```{r, echo = FALSE}

top_year <- consumption_totals |> 
  filter(fuel == "Total") |> 
  filter(period == max(period)) |> 
  pull(period)


bottom_year <- 2003 # hard coding for the quad
#bottom_year <- top_year - 15

data_use <- consumption_percent |> 
  filter(period == top_year | period == bottom_year) |> 
  mutate(percent_label = paste0(as.character(round(Percent * 100)), "%"), 
         nudge_factor = ifelse(period == top_year, 1, -1))

p <- data_use |> 
  ggplot() + aes(x = period, y = Percent, label = percent_label) + geom_point(aes(colour = factor(Fuel)), size = 3) + geom_line(aes(colour = factor(Fuel)), size = 1) + geom_text_repel(nudge_x = data_use$nudge_factor, size = 3.5) + scale_color_manual(values = fuel_colors, name = "") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black"), axis.title.y = element_blank()) + xlab("Year") + ggtitle("Change in Energy Consumption") + scale_y_continuous(labels = scales::percent) + scale_x_continuous(breaks = c(bottom_year, top_year), limits = c((bottom_year - 3), (top_year + 3))) +
  labs(caption = paste0("Source: Energy Information Administration\nAccessed ", today))

p

suppressMessages(
 p |> 
  download_this(
    output_name = "Change in Energy Consumption", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)


```

   



```{r, echo = FALSE}

wind <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key,
      "&facets[seriesId][]=WYTCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )

wood_waste <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key,
      "&facets[seriesId][]=WWTCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )

ethanol <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key,
      "&facets[seriesId][]=EMTCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )

biodiesel <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key,
      "&facets[seriesId][]=BDTCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )

solar <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key,
      "&facets[seriesId][]=SOTCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )

hydro <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key,
      "&facets[seriesId][]=HYTCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )

geothermal <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key,
      "&facets[seriesId][]=GETCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )

ethanol_loss_coproduct <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key,
      "&facets[seriesId][]=EMLCB&facets[stateId][]=MN&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )
#define color scheme

renewable_colors <- c("Wind" = "#9BCBEB", 
                      "Solar" = "#FFC845", 
                      "Hydroelectric" = "#008EAA", 
                      "Biomass" = "#8D3F2B")


api_cleanup <- function(x, fuel){
  
  x <- fromJSON(rawToChar(x$content))
  
  x$response$data |> 
    tibble() |> 
    mutate(fuel_type = fuel, 
           value = as.numeric(value) / 1000,  #convert to trillion BTUs
           period = as.numeric(period)) |>
    filter(period >= 2003) |> 
    select(period, fuel_type, value)
  
}

wind <- api_cleanup(wind, "Wind")

wood_waste <- api_cleanup(wood_waste, "Wood & Waste")

ethanol <- api_cleanup(ethanol, "Ethanol")

biodiesel <- api_cleanup(biodiesel, "Biodiesel")

solar <- api_cleanup(solar, "Solar")

hydro <- api_cleanup(hydro, "Hydroelectric")

geothermal <- api_cleanup(geothermal, "Geothermal")

ethanol_loss_coproduct <- api_cleanup(ethanol_loss_coproduct, "Ethanol Losses and Coproducts")

total_renewables <- wind |> 
  bind_rows(wood_waste) |> 
  bind_rows(ethanol) |> 
  bind_rows(biodiesel) |> 
  bind_rows(solar) |> 
  bind_rows(hydro) |> 
  bind_rows(geothermal) |> 
  bind_rows(ethanol_loss_coproduct)

total_renewables |> 
  ggplot() +aes(x = period, y = value, color = fuel_type) + geom_line() + 
  ylab("Trillion BTUs") + xlab("Year")

```

Renewables as a percent of total consumption - MN vs US

```{r, echo = FALSE}

area_colors <- c("Minnesota" = "#78BE21", "United States" = "#000000")

mn_consumption <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key, 
      "&facets[stateId][]=MN&facets[seriesId][]=RETCB&facets[seriesId][]=TETCB&start=2003&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )
  

us_consumption <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/seds/data/?frequency=annual&data[0]=value&api_key=", 
      eia_key, 
      "&facets[stateId][]=US&facets[seriesId][]=RETCB&facets[seriesId][]=TETCB&start=2003&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
      )
  )

api_cleaner <- function(x){
  
  x <- fromJSON(rawToChar(x$content))
  
  x <- x$response$data |> 
    select(period, seriesId, stateDescription, value) |> 
    pivot_wider(names_from = "seriesId", values_from = "value") |> 
    mutate(percent_renewable = as.numeric(RETCB) / as.numeric(TETCB), 
           period = as.numeric(period), 
           percent_label = case_when(
             period == max(period) ~ paste0(as.character(round((percent_renewable * 100), 0)), "%"), 
             TRUE ~ ""
             )) |> 
    select(period, stateDescription, percent_renewable, percent_label)
  
}

mn_consumption <- api_cleaner(mn_consumption)

us_consumption <- api_cleaner(us_consumption)

total_consumption <- mn_consumption |> 
  bind_rows(us_consumption) 

top_year = max(mn_consumption$period)

bottom_year = min(mn_consumption$period)

p <- total_consumption |> 
  ggplot() + aes(x = period, y = percent_renewable, color = stateDescription) + geom_line(linewidth = 1) + 
  geom_text(aes(label = percent_label), nudge_x = 1, show.legend = FALSE) + 
  scale_color_manual(values = area_colors, name = "") + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) + 
  scale_y_continuous(labels = scales::percent, limits = c(0, .2)) + scale_x_continuous(name = "Year", limits = c(bottom_year, top_year + 3), breaks = seq(bottom_year, top_year, by = 5)) + 
   ggtitle("Minnesota and US Renewable Consumption Trend") + 
  labs(caption = paste0("Source: Energy Information Administration\nAccessed ", today)) +
  ylab("Percent of Total Energy Consumption") + xlab("Year")

p

suppressMessages(
 p |> 
  download_this(
    output_name = "Renewable Consumption Trend in US and MN", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)


```













