---
title: "Natural Gas"
output: html_document
---



```{r, echo = FALSE, include = FALSE}

library(tidyverse)
library(jsonlite)
library(httr)
library(janitor)
library(downloadthis)
library(lubridate)
library(ggrepel)
library(data.table)
library(zoo)
library(keyring)

eia_key <- key_get("eia_api")

today <- format(Sys.Date(), format = "%m-%d-%Y")

henry_hub <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/natural-gas/pri/fut/data/?api_key=", 
      eia_key,
      "&frequency=monthly&data[0]=value&facets[series][]=RNGWHHD&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )

henry_hub <- fromJSON(rawToChar(henry_hub$content))

henry_hub <- tibble(henry_hub$response$data) 

```

Download Monthly Henry Hub Spot Price Data

```{r, echo = FALSE}

data_use <- henry_hub |> 
  select(period, `product-name`, value, units)

DT::datatable(data_use, rownames = FALSE)

suppressMessages(
  data_use |> 
  download_this(
    output_name = "Henry Hub Natural Gas Spot Price", 
    output_extension = ".xlsx", 
    button_label = "Download Data",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)
```

&nbsp;
&nbsp;

```{r, echo = FALSE}
price_label <- paste0("$", as.character(henry_hub |> 
  filter(period == max(period)) |> 
  pull(value)))

vline_russia <- henry_hub |>
  mutate(period = ym(period)) |> 
  filter(period == "2022-02-01") |> 
  pull(period)

vline_yuri <- henry_hub |> 
  mutate(period = ym(period)) |> 
  filter(period == "2021-02-01") |> 
  pull(period)

p <- henry_hub |> 
  mutate(month_label = period, 
         period = ym(period), 
         value = as.numeric(value), 
         year = year(period)) |>
  arrange(desc(period)) |>
  mutate(price_label = ifelse(period == max(period), price_label, "")) |> 
  slice(1:60) |> 
  select(period, value, price_label) |> 
  ggplot() + aes(x = period, y = value) + geom_line(color = "#000000", size = 1) +  
  geom_text_repel(aes(label = price_label), nudge_x = 1) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), 
        axis.title.x = element_blank()) + 
  ylab("Dollar per MMBTU") + ggtitle("Monthly Henry Hub Natural Gas Spot Price") + 
  labs(caption = paste0("Source: Energy Information Administration\nAccessed ", today)) + 
  geom_vline(xintercept = vline_russia) + annotate("text", x = vline_russia - 20, y = 7, label = "Russia Invades Ukraine", angle = 90, size = 3.5, color = "black") + 
  geom_vline(xintercept = vline_yuri) + annotate("text", x = vline_yuri - 20, y = 7, label = "Winter Storm Yuri", angle = 90, size = 3.5, color = "black") + ylim(0, 10)
  

p

suppressMessages(
  p |> 
  download_this(
    output_name = "Henry Hub Natural Gas Spot Price", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)

ggsave("C:/Users/dduffy/OneDrive - State of Minnesota - MN365/Frequently Used Graphs/Natural Gas Prices/Henry Hub Natural Gas Spot Price.png", p)
  
```


Natural Gas Electricity Generation Since 2021

```{r, echo = FALSE}

start_date <- "2021-01-01"

monthly_gen <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/electricity/electric-power-operational-data/data?api_key=", 
      eia_key,
      "&data[]=generation&frequency=annual&facets[location][]=MN&frequency=monthly&facets[sectorid][]=99&start=", start_date))

monthly_gen <- fromJSON(rawToChar(monthly_gen$content))


cleanup <- function(x){
  
  data_use <- x$response$data |> 
    tibble() |> 
    clean_names() |> 
    mutate(generation = as.numeric(generation)) |> 
    select(period, fuel_type_description, generation) |>
    filter(fuel_type_description %in% c("natural gas", "all fuels")) |> 
    pivot_wider(names_from = fuel_type_description, values_from = generation) |>
    arrange(period) |>
    mutate(period = ym(period),
          year = year(period),
          `Natural Gas` = rollmean(`natural gas`, 12, na.pad = T, align = "right"),
          all = rollmean(`all fuels`, 12, na.pad = T, align = "right")) |>
    mutate(`Natural Gas` = `Natural Gas` / all) |> 
    select(period, `Natural Gas`) |>
    pivot_longer(!period, names_to = "fuel", values_to = "generation") |> 
    filter(complete.cases(generation)) |> 
    arrange(desc(period)) 
  
  return(data_use)

}

monthly_gen <- cleanup(monthly_gen)

min_date <- min(monthly_gen$period)

max_date <- max(monthly_gen$period)

vline_russia <- monthly_gen |> 
  filter(period == "2022-02-01") |> 
  pull(period)

p <- monthly_gen |> 
  mutate(label = ifelse(period == max_date, paste0(as.character(round(generation * 100)), "%"), "")) |> 
  ggplot() + aes(x = period, y = generation) + geom_line(aes(color = fuel), size = 1.2)  + 
  scale_color_manual(values = "#8D3F2B", name = "", guide = "none") + 
  scale_x_date(breaks = seq(from = min_date, to = max_date, by = "6 months")) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), 
        axis.text.x = element_text(angle = 45, vjust = .5), axis.title.x = element_blank()) +
  guides(fill = "none") +
  scale_y_continuous(labels = scales::percent, name = "12 Month Moving Average", limits = c(0, .5)) + ggtitle("Natural Gas Volatility in Electricity Generation") + 
   geom_text_repel(aes(label = label), nudge_x = 1.5, size = 3.5) + 
  labs(caption = paste0("Source: Energy Information Administration\nAccessed ", today))  + 
  geom_vline(xintercept = vline_russia) +
  annotate("text", x = vline_russia - 20, y = .35, label = "Russia Invades Ukraine", angle = 90, size = 3.5, color = "black")

p

suppressMessages(
  p |> 
  download_this(
    output_name = "Natural Gas Volatility", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)

```



