---
title: "Renewables and Coal"
author: "Dennis Duffy"
date: "2022-10-04"
output: html_document
---

Percent of electricity generated by coal

```{r, echo = F}
library(tidyverse)
library(jsonlite)
library(httr)
library(janitor)
library(downloadthis)
library(data.table)
library(ggrepel)
library(rio)
library(lubridate)
library(zoo)
library(keyring)

eia_key <- key_get("eia_api")

today <- format(Sys.Date(), format = "%m-%d-%Y")

raw_generation_mn <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/electricity/electric-power-operational-data/data?api_key=",
      eia_key,
      "&data[]=generation&frequency=annual&facets[location][]=MN&facets[sectorid][]=99"
    )
  )

raw_generation_us <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/electricity/electric-power-operational-data/data?api_key=",
      eia_key,
      "&data[]=generation&frequency=annual&facets[location][]=US&facets[sectorid][]=99"
    )
  )

raw_generation_mn <- fromJSON(rawToChar(raw_generation_mn$content))

raw_generation_us <- fromJSON(rawToChar(raw_generation_us$content))

cleanup <- function(x, area){
  
  x <- x$response$data |> 
    tibble() |> 
    clean_names() |> 
    mutate(period = as.numeric(period), 
           generation = as.numeric(generation)) |> 
    select(period, fuel_type_description, generation) |> 
    filter(fuel_type_description %in% c("all fuels", "all coal products")) |> 
    pivot_wider(names_from = fuel_type_description, values_from = generation) |> 
    rename(coal = `all coal products`) |> 
    mutate(across(coal, ~ . / `all fuels`)) |> 
    select(period, coal) |> 
    mutate(area = area)
  
  return(x)
  
}

mn_coal <- cleanup(raw_generation_mn, "Minnesota")

us_coal <- cleanup(raw_generation_us, "US")

area_colors <- c("Minnesota" = "#008EAA", "US" = "#000000")

top_year = max(mn_coal$period)

bottom_year = min(mn_coal$period)

p <- mn_coal |> 
  bind_rows(us_coal) |> 
  mutate(percent_label = ifelse(period == max(period), paste0(as.character(round(coal * 100)), "%"), "")) |> 
  ggplot() + aes(x = period, y = coal) + geom_line(aes(color = factor(area)), size = 1) + scale_color_manual(values = area_colors, name = "") + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), axis.title.y = element_blank()) + 
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) + scale_x_continuous(name = "Year", limits = c(bottom_year, top_year + 3), seq(bottom_year, top_year, by = 5)) + 
  geom_text_repel(aes(label = percent_label), nudge_x = 1) + ggtitle("Minnesota and US Coal Generated Electricity Trend") + 
  labs(caption = paste0("Source: Energy Information Administration\nAccessed ", today)) 

p

suppressMessages(
  p |> 
  download_this(
    output_name = "Minnesota and US Coal Electricity Trend", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)

ggsave("C:/Users/dduffy/OneDrive - State of Minnesota - MN365/Frequently Used Graphs/Coal/Minnesota and US Coal Electricity Trend.png", p)

```

Carbon Intensity of Electricity

```{r, echo = F}
emissions_data <- rio::import("https://www.eia.gov/electricity/data/state/emission_annual.xlsx") |> 
  tibble() %>%
  clean_names() %>%
  filter(state %in% c("MN", "US-TOTAL"),
         producer_type == "Total Electric Power Industry", 
         energy_source == "All Sources") 


cleanup <- function(x, area){
  
  x <- x$response$data |> 
    tibble() |> 
    clean_names() |>
    mutate(period = as.numeric(period), 
           generation = as.numeric(generation)) |> 
    select(period, fuel_type_description, generation) |> 
    filter(fuel_type_description %in% c("all fuels")) |> 
    mutate(area = area)
  
  return(x)
  
}

us_gen <- cleanup(raw_generation_us, "US")

mn_gen <- cleanup(raw_generation_mn, "Minnesota")

us_carbon_intensity <- emissions_data |> 
  filter(state == "US-TOTAL") |> 
  select(year, co2_metric_tons) |> 
  filter(year %in% us_gen$period) |> 
  left_join(us_gen, by = c("year" = "period")) |> 
  mutate(carbon_intensity = co2_metric_tons / (generation * 1000)) |> #standardizing units to be consistent with past quads
  select(year, carbon_intensity, area)
 

mn_carbon_intensity <- emissions_data |> 
  filter(state == "MN") |> 
  select(year, co2_metric_tons) |> 
  filter(year %in% us_gen$period) |> 
  left_join(mn_gen, by = c("year" = "period")) |> 
  mutate(carbon_intensity = co2_metric_tons / (generation * 1000)) |> #standardizing units to be consistent with past quads
  select(year, carbon_intensity, area)

area_colors <- c("Minnesota" = "#008EAA", "US" = "#000000")

bottom_year <- min(us_carbon_intensity$year)

top_year <- max(us_carbon_intensity$year)

p <- us_carbon_intensity |> 
  bind_rows(mn_carbon_intensity) |> 
  mutate(percent_label = ifelse(year == max(year), as.character(round(carbon_intensity, digits = 2)), "")) |> 
  ggplot() + aes(x = year, y = carbon_intensity) + geom_line(aes(color = area), size = 1) + scale_color_manual(values = area_colors, name = "") + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  scale_y_continuous(name = "Carbon Intensity (Tons CO2/MWh)", limits = c(0, 1)) + scale_x_continuous(name = "Year", limits = c(bottom_year, top_year + 3), seq(bottom_year, top_year, by = 5)) + ggtitle("Carbon Intensity of Electricity") + 
  geom_text_repel(aes(label = percent_label), nudge_x = 1.5) + 
  labs(caption = paste0("Source: Energy Information Administration\nAccessed ", today)) 

p

suppressMessages(
  p |> 
  download_this(
    output_name = "Carbon Intensity of Electricity", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)

ggsave("C:/Users/dduffy/OneDrive - State of Minnesota - MN365/Frequently Used Graphs/Coal/Carbon Intensity of Electricity.png", p)


```


Economic and Seasonal Dispatch of Coal
```{r, echo = F}
start_date <- paste(as.character(year(Sys.Date()) - 4), "12", "01", sep = "-")

monthly_gen <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/electricity/electric-power-operational-data/data?api_key=",
      eia_key,
      "&data[]=generation&frequency=monthly&facets[location][]=MN&facets[sectorid][]=99&start=",
      start_date
    )
  )

monthly_gen <- fromJSON(rawToChar(monthly_gen$content))

cleanup <- function(x){
  
   coal_table <- x$response$data |>
    tibble() |>
    clean_names() |>
    mutate(generation = as.numeric(generation),
           period = ym(period),
           year = year(period)) |>
    select(period, fuel_type_description, generation) |>
    filter(fuel_type_description %in% c("all coal products")) |>
    arrange(period) |>
    rename(fuel = fuel_type_description)

   return(coal_table)
  
}

fuel_colors <- c("Renewables" = "#78BE21", "Coal" = "#000000", "Natural Gas" = "#8D3F2B")

monthly_gen <- cleanup(monthly_gen)

min_date <- min(monthly_gen$period)

max_date <- max(monthly_gen$period)


p <- monthly_gen |> 
  ggplot() + aes(x = period, y = generation, group = 1) + geom_line(size = 1.2) +
  scale_color_manual(values = fuel_colors, name = "") +
  scale_x_date(breaks = seq(from = min_date, to = max_date, by = "6 months")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"),
        axis.text.x = element_text(angle = 45, vjust = .5), axis.title.x = element_blank()) +
  scale_y_continuous(name = "Thousand Megawatthours") + ggtitle("Seasonal Dispatch of Coal") +
  scale_alpha_manual(values = c(1, .5, 0)) +
  labs(caption = paste0("Source: Energy Information Administration\nAccessed ", today)) 

p

suppressMessages(
  p |> 
  download_this(
    output_name = "Seasonal Dispatch of Coal", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)

```


Minnesota Electricity Generation Transition
```{r, echo = F}
start_date <- as.Date(paste(as.character(year(Sys.Date()) - 3), "12", "01", sep = "-"))

monthly_gen <- 
  GET(
    paste0(
      "https://api.eia.gov/v2/electricity/electric-power-operational-data/data/?api_key=",
      eia_key,
      "&frequency=monthly&data[0]=generation&facets[location][]=MN&facets[fueltypeid][]=ALL&facets[fueltypeid][]=AOR&facets[fueltypeid][]=COW&facets[fueltypeid][]=HYC&facets[fueltypeid][]=NG&facets[sectorid][]=99&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"
    )
  )

monthly_gen <- fromJSON(rawToChar(monthly_gen$content))


cleanup <- function(x){
  
  x$response$data |> 
    tibble() |> 
    clean_names() |> 
    mutate(generation = if_else(is.na(as.numeric(generation)), 0, as.numeric(generation))) |>
    select(period, fuel_type_description, generation) |>
    filter(fuel_type_description %in% c("all renewables", "conventional hydroelectric", "all coal products", "natural gas", "all fuels")) |> 
    pivot_wider(names_from = fuel_type_description, values_from = generation) |>
    arrange(period) |>
    mutate(renewables = `all renewables` + `conventional hydroelectric`,
          period = ym(period),
          year = year(period),
          Coal = rollmean(`all coal products`, 12, na.pad = T, align = "right"),
          Renewables = rollmean(renewables, 12, na.pad = T, align = "right"),
          `Natural Gas` = rollmean(`natural gas`, 12, na.pad = T, align = "right"),
          all = rollmean(`all fuels`, 12, na.pad = T, align = "right")) |>
    filter(period >= start_date) |> 
    mutate(across(c(Coal, Renewables, `Natural Gas`), .fns = ~. / all)) |>
    select(period, Coal, Renewables, `Natural Gas`) |>
    pivot_longer(!period, names_to = "fuel", values_to = "generation") |> 
    filter(complete.cases(generation))

}

monthly_gen <- cleanup(monthly_gen)

min_date <- min(monthly_gen$period)

max_date <- max(monthly_gen$period)

p <- monthly_gen |> 
  mutate(label = ifelse(period == max_date, paste0(as.character(round(generation * 100)), "%"), "")) |> 
  ggplot() + aes(x = period, y = generation) + geom_line(aes(color = fuel), size = 1.2)  + 
  scale_color_manual(values = fuel_colors, name = "") + 
  scale_x_date(breaks = seq(from = min_date, to = max_date, by = "6 months")) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black"), 
        axis.text.x = element_text(angle = 45, vjust = .5), axis.title.x = element_blank()) +
  scale_y_continuous(labels = scales::percent, name = "12 Month Moving Average", limits = c(0, .5)) + ggtitle("Minnesota Electricity Generation Transition") + 
   geom_text_repel(aes(label = label), nudge_x = 1.5, size = 3.5) + 
  labs(caption = paste0("Source: Energy Information Administration\nAccessed ", today)) 

p

suppressMessages(
  p |> 
  download_this(
    output_name = "Minnesota Electricity Generation Transition", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)

ggsave("C:/Users/dduffy/OneDrive - State of Minnesota - MN365/Frequently Used Graphs/Renewables/Minnesota Electricity Generation Transition.png", p)

```









