---
title: "Solar"
output: html_document
---


```{r, echo = FALSE, include = FALSE}

library(tidyverse)
library(ggrepel)
library(downloadthis)
library(readxl)
library(writexl)
library(duckdb)

# Analysts change this path as necessary

db_path <- "I:/Enrgy_div/SEO/CleanEnegyTechUnit/CET Projects/Data Repository/generator_database_shared/generator_database_dbt/dev.duckdb"

db <- dbConnect(duckdb::duckdb(), db_path, read_only = TRUE)

# Change query to reflect changes in year
solar_query <- 
  dbSendQuery(
    db, "
      SELECT *, 
        ROUND(nameplate_mw * 1000) AS kwac
      FROM main.mart_combined__solar_capacity 
      WHERE year_interconnected <= 2024
    ")

raw_solar <- dbFetch(solar_query) |> 
  tibble() |> 
  mutate(customer_type = str_to_title(customer_type))

dbClearResult(solar_query)
dbDisconnect(db, shutdown = TRUE)


```

Download comprehensive solar data

```{r, echo = FALSE}
raw_solar |> 
  download_this(
    output_name = "Solar Capacity in Minnesota", 
      output_extension = ".xlsx", 
      button_label = "Download Data",
      button_type = "success", 
      has_icon = TRUE,
      icon = "fa fa-save"
  )
```

&nbsp;
&nbsp;

Solar data to post to the website

```{r, echo = FALSE}

raw_solar |> 
  group_by(year_interconnected, customer_type) |> 
  summarise(kwac = sum(kwac, na.rm = TRUE)) |> 
  download_this(
    output_name = "Summary of Solar Capacity in Minnesota", 
      output_extension = ".xlsx", 
      button_label = "Download Data",
      button_type = "success", 
      has_icon = TRUE,
      icon = "fa fa-save"
  )

```

&nbsp;
&nbsp;

Solar aggregate capacity by year

```{r, echo = FALSE}

total_solar <- paste(round(sum(raw_solar$kwac, na.rm = T)/1000, digits = 2), "MW", sep = " ")

year_limit <- max(raw_solar$year_interconnected, na.rm = TRUE) + 3

top_year <- max(raw_solar$year_interconnected, na.rm = TRUE)

bottom_year <- max(raw_solar$year_interconnected, na.rm = TRUE) - 15

p <- raw_solar |>
  filter(complete.cases(year_interconnected)) |> 
  group_by(year_interconnected) |> 
  summarize(total_kwac = sum(kwac, na.rm = T)) |> 
  mutate(cumulative_kwac = cumsum(total_kwac), 
         total_label = ifelse(year_interconnected == max(year_interconnected), total_solar, "")) |> 
  filter(year_interconnected >= max(year_interconnected) - 15) |> 
  ggplot() + aes(x = year_interconnected, y = cumulative_kwac / 1000) + geom_line(color = "#FFC845", size = 1) + 
  scale_x_continuous(limits = c(bottom_year, year_limit), breaks = seq(bottom_year, top_year, by = 5), name = "Year") + 
  geom_text_repel(aes(label = total_label), nudge_x = 1) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) + ylab("Cumulative Solar Capacity (MW/AC)") + ggtitle("Cumulative Solar Capacity") + 
  labs(caption = "Source: Minnesota Public Utilities Commision Annual Distributed Generation Reports,\nEnergy Information Administration Form EIA-860")

p

suppressMessages(
  p |> 
  download_this(
    output_name = "Cumulative Solar Capacity", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)

ggsave("C:/Users/dduffy/OneDrive - State of Minnesota - MN365/Frequently Used Graphs/Solar/Cumulative Solar Capacity.png", p)

```
&nbsp;
&nbsp;

Solar Installation Type Trend

```{r, echo = FALSE}

installation_colors <- c("Other" = "#003865", "Community" = "#78BE21", "Utility" = "#008EAA")

installation_labels <- raw_solar |> 
  mutate(installation_type = case_when(
    customer_type %in% c("Community Solar Garden", "community solar garden") ~ "Community", 
    customer_type %in% c("utility", "Utility") ~ "Utility", 
    TRUE ~ "Other"
  )) |> 
  group_by(installation_type) |> 
  summarise(total_mw_label = trunc(sum(kwac, na.rm = TRUE) / 1000))

p <- raw_solar |> 
  filter(complete.cases(year_interconnected)) |> 
  mutate(installation_type = case_when(
    customer_type == "Community Solar Garden" ~ "Community", 
    customer_type %in% c("utility", "Utility") ~ "Utility", 
    TRUE ~ "Other"
  )) |> 
  group_by(year_interconnected, installation_type) |> 
  summarise(total_mw = sum(kwac, na.rm = TRUE) / 1000) |>
  ungroup() |> 
  group_by(installation_type) |> 
  mutate(cumulative_mw = cumsum(total_mw)) |> 
  filter(year_interconnected >= bottom_year) |> 
  left_join(installation_labels, by = "installation_type") |> 
  mutate(total_mw_label = ifelse(year_interconnected == max(year_interconnected), paste0(as.character(total_mw_label), " MW"), "")) |> 
  ggplot() + aes(x = year_interconnected, y = cumulative_mw, fill = installation_type) + geom_line(aes(color = factor(installation_type)), size = 1) + 
  scale_color_manual(values = installation_colors, name = "") + geom_text_repel(aes(label = total_mw_label), nudge_x = .5, size = 3.5) + 
  scale_x_continuous(limits = c(bottom_year - 1, year_limit), breaks = seq(bottom_year, top_year, by = 5), name = "Year") + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  ylab("Cumulative Solar Capacity (MW/AC)") + ggtitle("Minnesota's Cumulative Solar Installations by Type") + 
  labs(caption = "Source: Minnesota Public Utilities Commision Annual Distributed Generation Reports,\nEnergy Information Administration Form EIA-860")

p

suppressMessages(
  p |> 
  download_this(
    output_name = "Cumulative Solar Capacity by Type", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)

ggsave("C:/Users/dduffy/OneDrive - State of Minnesota - MN365/Frequently Used Graphs/Solar/Cumulative Solar Capacity by Type.png", p)
```


&nbsp;
&nbsp;

Solar Installations by year

```{r, echo = FALSE}

installation_colors <- c("Other" = "#003865", "Community" = "#78BE21", "Utility" = "#008EAA")

top_year <- max(raw_solar$year_interconnected, na.rm = TRUE)

bottom_year <- max(raw_solar$year_interconnected, na.rm = TRUE) - 8

annual_labels <- raw_solar |> 
  filter(complete.cases(year_interconnected)) |> 
  group_by(year_interconnected) |> 
  summarise(total_mw = round(sum(kwac, na.rm = TRUE) / 1000)) |> 
  filter(year_interconnected >= max(year_interconnected) - 8)

p <- raw_solar |> 
  filter(complete.cases(year_interconnected)) |> 
  mutate(installation_type = case_when(
    customer_type %in% c("Community Solar Garden", "community solar garden") ~ "Community", 
    customer_type %in% c("utility", "Utility") ~ "Utility", 
    TRUE ~ "Other"
  )) |> 
  filter(year_interconnected >= max(year_interconnected) - 8) |> 
  group_by(year_interconnected, installation_type) |> 
  summarise(total_mw = sum(kwac, na.rm = TRUE) / 1000) |> 
  filter(complete.cases(year_interconnected)) |> 
  mutate(installation_type = factor(installation_type, levels = c("Utility", "Community", "Other"))) |> 
  ggplot() + aes(x = year_interconnected, y = total_mw, fill = installation_type) + geom_bar(stat = "identity", position = "stack") + 
  scale_fill_manual(values = installation_colors, name = "") + geom_text(aes(year_interconnected, total_mw + 20, label = total_mw, fill = NULL), data = annual_labels) + 
  scale_x_continuous(limits = c(bottom_year - 1, top_year + 1), breaks = c(bottom_year:top_year), name = "Year") + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  ylab("Annual Additions (MW/AC)") + ggtitle("Minnesota's Annual Solar Installations") + 
  labs(caption = "Source: Minnesota Public Utilities Commision Annual Distributed Generation Reports,\nEnergy Information Administration Form EIA-860")

p

suppressMessages(
  p |> 
  download_this(
    output_name = "Annual Solar Installations", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)

ggsave("C:/Users/dduffy/OneDrive - State of Minnesota - MN365/Frequently Used Graphs/Solar/Annual Solar Installations.png", p)

```

&nbsp;
&nbsp;

Capacity by type of solar installation

```{r, echo = FALSE}
installation_colors <- c("Other" = "#003865", "Community" = "#78BE21", "Utility" = "#008EAA")

total_kwac <- sum(raw_solar$kwac, na.rm = TRUE)

p <- raw_solar |> 
  mutate(installation_type = case_when(
    customer_type %in% c("Community Solar Garden", "community solar garden") ~ "Community", 
    customer_type %in% c("utility", "Utility") ~ "Utility", 
    TRUE ~ "Other"
  )) |> 
  group_by(installation_type) |> 
  summarise(percent_gen = sum(kwac, na.rm = TRUE) / total_kwac) |> 
  mutate(gen_label = paste0(as.character(round(percent_gen * 100)), "%")) |> 
  ggplot() + aes(x = percent_gen, y = fct_reorder(as_factor(installation_type), percent_gen), fill = installation_type, label = gen_label) +
  geom_bar(stat = "identity") + scale_x_continuous(limits = c(0, 1)) + 
  scale_fill_manual(values = installation_colors, name = "") + 
  geom_text(nudge_x = .05) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank(), 
legend.position = "none") + 
  xlab("Percent of Solar Capacity") + ggtitle("Solar Capacity by Installation Type") + 
  labs(caption = "Source: Minnesota Public Utilities Commision Annual Distributed Generation Reports,\nEnergy Information Administration Form EIA-860")

p 

suppressMessages(
  p |> 
  download_this(
    output_name = "Solar Capacity by Installation Type", 
    output_extension = ".png", 
    button_label = "Download Plot",
    button_type = "success", 
    has_icon = TRUE,
    icon = "fa fa-save"
  )
)

ggsave("C:/Users/dduffy/OneDrive - State of Minnesota - MN365/Frequently Used Graphs/Solar/Solar Capacity by Installation Type.png", p)
```


